name: 'Versioning Checker'
description: 'Checks whether the APP_VERSION and CHANGELOG.md files have been updated on each PR'
icon: check-square
color: purple

inputs:
  tracked_files:
    description: 'Comma separated list of all file names that should be tracked.'
    required: true
    default: "APP_VERSION,CHANGELOG.md"

runs:
  using: 'docker'
  image: 'Dockerfile'
