name: 'Versioning Checker'
description: 'Checks whether the APP_VERSION and CHANGELOG.md files have been updated on each PR'
icon: check-square
color: purple

inputs:
  token:
    description: 'GitHub token created by workflow'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
