name: 'Versioning Checker'
description: 'GitHub action for verifying expected file changes on each PR. Deault behavior is to verify whether APP_VERSION and CHANGELOG.md files have been updated.'
icon: check-square
color: purple

inputs:
  tracked_files:
    description: 'Comma separated list of all file names that should be tracked.'
    required: true
    default: "APP_VERSION,CHANGELOG.md"
  fork_repo_name:
    description: "PRs from forked repos do not work by default. If this PR is from a forked repo, provide the new REPO_NAME: https://github.com/[REPO_NAME].git"
    required: true
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
