name: Versioning Checker
description: Check if APP_VERSION and CHANGELOG files have been updated
icon: file
color: purple

runs:
  using: 'node12'
  main: 'index.js'

  inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}

jobs:
  collect_changed_files:
    runs-on: ubuntu-latest
    name: Collect changed files
      steps:
        - name: Git diff
          id: git_diff
          run: echo '::set-output name=SELECTED_COLOR::green'
          