name: Health check extravaganza

# Triggers the workflow on pull request events for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  version_check:
    runs-on: ubuntu-latest
    name: Checks APP_VERSION and CHANGELOG.md files for updates.
    steps:
    - name: Run version checker
      uses: mwcodebase/versioning-checker@v2.3-test